Repository openedx/open-edx-proposals, pull requests merged in 2024-08, with the labels that each got.

#619 docs: Adding a rejected alternative to OEP-65 for Vite module federation
  oeps/architectural-decisions/oep-0065-arch-frontend-composability.rst
Labels: open-source-contribution

#616 docs: ADR to use React Query instead of Redux, update general JS/TS guidance
  oeps/best-practices/oep-0067-bp-tools-and-technology.rst
  oeps/best-practices/oep-0067/decisions/frontend/0002-redux.rst
  oeps/best-practices/oep-0067/decisions/frontend/0010-react-query.rst
Labels: open-source-contribution, core contributor, waiting for eng review

#598 docs: adding an ADR to OEP-65 about a unified platform repository
  oeps/architectural-decisions/oep-0065-arch-frontend-composability.rst
  oeps/architectural-decisions/oep-0065/decisions/0001-unified-platform-repository.rst
Labels: open-source-contribution, waiting for eng review

#615 Clarify how devDependencies should be used for NPM packages (OEP-67: Standard Tools and Technologies)
  oeps/best-practices/oep-0067-bp-tools-and-technology.rst
Labels: open-source-contribution, core contributor, waiting for eng review
